window.REMS44_STUDENTS = [
  {
    "id": "vintsiuk-andrii",
    "studentId": "2",
    "name": "Вінцюк Андрій Олександрович",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "vlasenko-dasha",
    "studentId": "3",
    "name": "Власенко Дар`я Андріївна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "hostryk-katya",
    "studentId": "6",
    "name": "Гострик Катерина Юріївна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "zholudenko-polina",
    "studentId": "10",
    "name": "Жолуденко Поліна Ігорівна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-11",
    "studentId": "11",
    "name": "Заярна Валерія Сергіївна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "kasieiev-danylo",
    "studentId": "13",
    "name": "Касєєв Данило Павлович",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "kolyshkin-andrii",
    "studentId": "15",
    "name": "Колишкін Андрій Юрійович",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-17",
    "studentId": "17",
    "name": "Кохан Ольга Сергіївна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "koshelieva-myroslava",
    "studentId": "18",
    "name": "Кошелєва Мирослава Сергіївна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-19",
    "studentId": "19",
    "name": "Краснянський Ростислав Віталійович",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "milenina-mariia",
    "studentId": "23",
    "name": "Міленіна Марія Олегівна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-24",
    "studentId": "24",
    "name": "Мойсієнко Віталіна Денисівна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-27",
    "studentId": "27",
    "name": "Неня Анастасія Миколаївна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "oleinykov-daniil",
    "studentId": "28",
    "name": "Олейников Данііл Денисович",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "pozniak-artur",
    "studentId": "31",
    "name": "Позняк Артур Русланович",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-32",
    "studentId": "32",
    "name": "Рожанківська Іванна Орестівна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "chynionova-dasha",
    "studentId": "34",
    "name": "Чиньонова Дар`я Олексіївна",
    "group": "РЕМС-44",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-1",
    "studentId": "1",
    "name": "Баленко Ілля Вікторович",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-4",
    "studentId": "4",
    "name": "Вознюк Олександра Миколаївна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-5",
    "studentId": "5",
    "name": "Волошина Дар'я Олександрівна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "davydova-svitlana",
    "studentId": "7",
    "name": "Давидова Світлана Олександрівна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-8",
    "studentId": "8",
    "name": "Данільчук Катерина Павлівна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-9",
    "studentId": "9",
    "name": "Дубина Віолетта Володимирівна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-12",
    "studentId": "12",
    "name": "Карпенко Рімма Романівна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-14",
    "studentId": "14",
    "name": "Кириленко Михайло Володимирович",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-16",
    "studentId": "16",
    "name": "Коткова Анастасія Андріївна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-20",
    "studentId": "20",
    "name": "Кропивка Маргарита Анатоліївна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-21",
    "studentId": "21",
    "name": "Лещинський Денис Віталійович",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "maksimova-samira",
    "studentId": "22",
    "name": "Максімова Саміра Вадимівна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-25",
    "studentId": "25",
    "name": "Мороз Марія Геннадіївна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-26",
    "studentId": "26",
    "name": "Мостова Яна Олегівна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-29",
    "studentId": "29",
    "name": "Павлова Катерина Володимирівна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "control-30",
    "studentId": "30",
    "name": "Піддубна Марія Анатоліївна",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  },
  {
    "id": "tashuta-artem",
    "studentId": "33",
    "name": "Ташута Артем Анатолійович",
    "group": "РЕМС-34",
    "role": "Режисура естради і шоу",
    "photo": "",
    "bio": [],
    "skills": [],
    "achievements": [],
    "socials": {
      "instagram": "",
      "tiktok": "",
      "youtube": "",
      "telegram": "",
      "facebook": "",
      "email": ""
    },
    "videos": [],
    "gallery": []
  }
];
